import json


#examples which events can be found within each category, examples are real events in Berlin, Bonn and Cologne
examples= {
    "party" : [
        "Sektgarten",
        "Neulich DJ Sessions with Magic",
        "Galaxy Unpacked - Rooftop-Party",
        "5PM club",
        "Soda Social Club",
        "FrühTanz",
        "PubCrawl Berlin",
        "Die ultimative Karaoke-Party",
        "Techno Thursday",
        "Beer Pong Night"
    ],
    "konzerte-und-musik": [
        "Liveband Karaoke",
        "Acoustic Moments",
        "Bonner Song Slam",
        "LIKE WAVES - Sommerkonzert",
        "Konzert Open Stage",
        "Kirmes in Endenich",
        "Kasalla",
        "Bob Dylan- Mitsing-Konzert",
        "Schäl Sick Sundowner",
        "Element of Crime",
        "Sofar Sounds",
        "Espresso-Konzert"
    ],
    "markt" : [
        "Trödelmarkt Spandau",
        "Flohmarkt Rathaus Schöneberg",
        "Berliner Fahrradmarkt",
        "Kunst- & Trödelmarkt Fehrbelliner Platz",
        "Kunstmarkt am Zeughaus",
        "Japanmarkt",
        "Rhein-Antik-, Kunst- und Designmarkt",
        "Pützcgens Markt",
        "Schallplattenbörse Bonn",
        "Fisch-& Genussmarkt",
        "Klamottentauschcafe",
        "thriftpark Köln"
    ],
    "theater": [
        "35 Tonnen",
        "Schnupperkurs bei Impro Köln",
        "Don Quijote",
        "Turandot oder Theater als Fest",
        "Schattentheater: LET IT BEE von OUTOFTHEBOX",
        "Romeo und Julia",
        "Musikantenstadl",
        "Improtheater IM FREIEN FALL",
        "Impro mit den Gorillas"
    ],
    "shows-und-performances": [
        "RebellComedy pres. 'Rebell's Most Wanted' Comedy Casting Show Halbfinale pt.II",
        "LAUGH LOUDER - Comedy & Improv presented by Comedian and host Rebecca Miro",
        "Pankower kleine Kunstbühne Zimmer 16 feiert: 60 Jahre Star Trek",
        "Voll Bingo!",
        "LACH MAL LAUDER  - Comedy & Impro",
        "Science Slam im Planetarium",
        "Danceperados of Ireland - Hooked",
        "FUN! - Open Mic @goldfinger",
        "Comedy Frischgezapft",
        "Kalkblatt - die Show zum verlieben",
        "Echtzeit Comedy -  Stand-Up am Freitag",
        "fem:me - eine politische Tanzperformance",
        "Kneipenquiz am Ebertplatz",
        "Sebastian Lehmann - Kinderzeit - Lesung & Comedy",
        "Kalk & Welk - Die fabelhaften Boomer Boys"
    ],
    "ausstellung": [
        "Nach Hitler",
        "Aufbruch in die Moderne",
        "Friede, Freude, Eierkuchen. Die Loveparade in den 90ern",
        "BONNER Sommer Salon 2025",
        "Cocktailführung (mit Kuratorinnen): Jupp Darchinger. Das Auge der Republik",
        "Freier Eintritt im LVR Museum",
        "Mythos Ming",
        "Welterbe in Japan - Photographien von Miyoshi Kazuyoshi",
        "Tuschewanderungen - Zeitgenössische Arbeiten auf Papier von Jianfeng Pan, 2014–2024",
        "Thematische Archivführung „Herbert Döring-Spengler im Rheinischen Bildarchiv",
        "Streetart aus Lateinamerika im Belgischen Viertel: Sonderausstellung 'Karte einer Fatamorgana', CECIRO, Uruguay",
        "VERNISSAGE >>> WHERE WITHIN",
        "Die lebende Stadt",
        "Zu Gast bei uns: Mission KI"
    ],
    "gesprochenes": [
        "Creative Writing",
        "Shared Reading",
        "Just a facade? Architecture tour in English",
        "Wohnzimmer Slam Berlin",
        "Berliner Literatur im Romanischen Café: Lesung und Gespräch mit Peggy Mädler",
        "Lachkater Stand Up Comedy Show in P-Berg",
        "Judith Hermann »Sommerhaus, später« Neuauflage eines Kultbuchs",
        "Eine Stunde Museum für Asiatische Kunst. Ein Rundgang in deutscher Sprache",
        "Marseille 1940 – Die große Flucht der Literatur",
        "Das Budapester Kaffeehaus - seine Vergangenheit und Zukunft",
        "Friedman im Gespräch: Wahnsinn",
        "GWÖ-Stammtisch Bonn",
        "Trägt Demokratie zu nachhaltigen Entscheidungen bei?",
        "Literarisches Ping-Pong mit René Klammer & David Jacobs",
        "Eröffnungsvortrag: Maja Göpel",
        "Der Rheinreden - U20 - Poetry-Slam Bonn · Jana Goller (Moderation)",
        "Hexenblut, das Relikt der Ahnin - historische Fantasy meets Reallife",
        "Queerfeministische Stand Up Comedy von FLINTA* und queer Comedians"

    ],
    "food-und-drinks": [
        "Aperol o'clock",
        "Mini-Afterwork Tasting",
        "All you can tapas",
        "Studi & Azubi Bistro Special",
        "Craft Brewery Tour",
        "Meet & Eat",
        "Wine Tasting Tour / Weinprobe mit Guide im Bulli durch Köln",
        "Dinner & New Friends: Flavours of Spain",
        "Bonner Wochenmarkt",
        "Sundowner Bar auf dem Dach",
        "Kulinarische Schnitzeljagd Bonn",
        "Kunstfrühstück",
        "Street Food Festival",
        "Weintasting",
        "Wochenmarkt am Hermannplatz",
        "Ökomarkt Hohenstaufenplatz",
        "Afterwork at ROMY",
        "Tipsy Tuesday",
        "Wochenmarkt am Bundesplatz"
    ],
    "aktiv-und-kreativ": [
        "Action & Paint Events Köln",
        "Bash Rooms Game Challenge",
        "planlos.in-Rätseltour 'Exit Ehrenfeld'",
        "MMC Studioführung - TV Backstage Tour",
        "planlos.in-Rätseltour 'Der verborgene Brunnen für Schulklassen'",
        "Stadtrallye & Schnitzeljagt im Belgischen Viertel",
        "Kostenloser Werkzeugverleih",
        "Stadtführung durch die Altstadt mit deinem Smartphone",
        "Holzwerkstatt",
        "Flynn's Inn Pub Quiz",
        "Schocken heißt das Spiel!",
        "Kneipen-Quiz",
        "Pub Quiz",
        "Quiz in der N8schicht by QUIZQUAMPERFEKT",
        "Karaoke Night",
        "Stadtführung Bonn",
        "Samavarta - Outdoor Escape Game, die neue Schnitzeljagd in Berlin",
        "Pubquiz with Simply Quiz – Open Air",
        "Tanzkurs Standard / Latein für Einsteiger direkt am Müggelsee"

    ],
    "feste-und-festival": [
        "CoSy Festival",
        "Fiesta Brasiliana",
        "Rocktreff 2025",
        "Pizza Street Festival",
        "Sunset Lounge Beats",
        "35 Jahre - Schokoladen Hoffest",
        "Heatwave - Der Sound gegen Intoleranz. Jugendfestival Reinickendorf",
        "Viva la Green",
        "Red Rocket Festival",
        "Feierabendmarkt auf dem Hermeskeiler Platz",
        "Weinfest am Rhein",
        "Flunkyball Turnier auf dem CAMPUS Garten",
        "CSD Bonn Beethovens Bunte 2025",
        "CAMPUS FESTIVAL 2025",
        "Symphony Swing",
        "Jeck im Sunnesching 2025 - Das Festival in Bonn"
    ],
    "sport": [
        "JUGAD pick-up football / pick-up Soccer",
        "Aerobic - Sport im Park",
        "Outdoor Fitness - Sport im Park",
        "Ashtanga Yoga",
        "Community Run",
        "Tanzabend & Workshops in der Severinstorburg! SALSA, BACHATA & RUEDA",
        "Tischtennis-Rundlauf-Turnier am Ebertplatz",
        "oliver‘s running club",
        "SUP KURS",
        "RUN-N-RAVE",
        "Tango @ Clärchens Ballhaus"
    ],
    "film": [
        "Der phönizische Meisterstreich",
        "Tod eines Handlungsreisenden",
        "Freiluftkino: La La Land",
        "Banff Tour 2025",
        "Freiluftkino im Körnerpark zeigt: Wishing on a Star",
        "COMMUNITY SNEAK PREVIEW",
        "Superman",
        "All Under the Moon",
        "Kurzfilmfest für SchülerInnen '.mov' 2025",
        "Sneak Preview - Deutsche Fassung",
        "The English Sneak Preview",
        "Kino für Menschenrecht: The Great Green Wall"
    ],
    "kinder-und-familien": [
        "Ferienangebot: Der Rhein. Leben am Fluss",
        "Lesung und Fragerunde: WAS IST WAS Grüne Energie mit Dr. Frank Frick",
        "Tanzcamp für Grundschulkinder 'Zeitreise durch die Tanzwelt'",
        "Pelemele - Das große Familienkonzert",
        "Mädchenkreis",
        "Köln liest für Pänz",
        "OHRENschmausen",
        "Kinder Akrobatik 9-11 Jahre",
        "Waldzeit Köln „Krabbelnd die Natur entdecken“",
        "Clown Olli | SOMMER KÖLN",
        "Das Universum zum Anfassen im Zeiss-Großplanetarium",
        "Auroras Magischer Würfel - Outdoor Escape für Familien",
        "Väter-Café",
        "Family Sundays"
    ]
}
with open("example_categories.json", "w") as f:
    json.dump(examples, f, indent=4, ensure_ascii=False)